apiVersion: v1
kind: Service
metadata:
  name: {{ include "weather-app-helm.name" . }}-svc
  labels:
    app: {{ include "weather-app-helm.name" . }}
spec:
  selector:
    app: {{ include "weather-app-helm.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
status:
    loadBalancer: {}
